backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: "static/images/uploads"
public_folder: "/images/uploads"
collections:
  - name: "blog"
    label: "Blog"
    folder: "blog/posts"
    create: true
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    extension: "md"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - label: "Tags"
        name: "tags"
        widget: "list"
        field: { label: Name, name: name, widget: string, default: "tag" }
      - {
          label: "Cover Image",
          name: "coverImage",
          widget: "image",
          required: false,
        }
      - { label: "Description", name: "description", widget: "markdown" }
      - { label: "Body", name: "body", widget: "markdown" }
