backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: "assets/images/uploads"
public_folder: "/assets/static"
collections:
  - name: "blog"
    label: "Blog"
    folder: "src/blog/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - label: "Tags"
        name: "tags"
        widget: "list"
      - {
          label: "Cover Image",
          name: "coverImage",
          widget: "image",
          required: false,
        }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
